import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.3.0'
    id 'org.jetbrains.kotlin.kapt' version '2.3.0'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // owo lib
    maven { url 'https://maven.wispforest.io' }
    // fabric permissions api
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    exclusiveContent {
        forRepository {
            maven { url = "https://api.modrinth.com/maven" }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

    // TODO: Remove owo-lib (and kapt)
    kapt modImplementation("io.wispforest:owo-lib:${project.owo_version}")
    include "io.wispforest:owo-sentinel:${project.owo_version}"
    modImplementation "me.lucko:fabric-permissions-api:${project.permissions_api_version}"
    modLocalRuntime "maven.modrinth:modmenu:${project.modmenu_version}"

    include implementation("io.ktor:ktor-server-netty-jvm:${project.ktor_version}")
    include implementation("io.ktor:ktor-server-content-negotiation-jvm:${project.ktor_version}")
    include implementation("io.ktor:ktor-serialization-kotlinx-json-jvm:${project.ktor_version}")
    include implementation("io.ktor:ktor-server-auth-jvm:${project.ktor_version}")
    // Don't include Swagger dependencies in built jar - only for in dev
    implementation("io.ktor:ktor-server-openapi-jvm:${project.ktor_version}")
    implementation("io.ktor:ktor-server-swagger-jvm:${project.ktor_version}")

    include implementation("org.jetbrains.exposed:exposed-core:${project.exposed_version}")
    include implementation("org.jetbrains.exposed:exposed-jdbc:${project.exposed_version}")
    include implementation("org.jetbrains.exposed:exposed-dao:${project.exposed_version}")
    include implementation("org.jetbrains.exposed:exposed-kotlin-datetime:${project.exposed_version}")
    include implementation("org.xerial:sqlite-jdbc:${project.sqlite_version}")
    include implementation("mysql:mysql-connector-java:${project.mysql_version}")

    // Inclusions required for Ktor dependencies
    include "io.ktor:ktor-server-core-jvm:${project.ktor_version}"
    include "io.ktor:ktor-utils:${project.ktor_version}"
    include "io.ktor:ktor-io-jvm:${project.ktor_version}"
    include "io.ktor:ktor-http-jvm:${project.ktor_version}"
    include "io.ktor:ktor-serialization-jvm:${project.ktor_version}"
    include "io.ktor:ktor-serialization-kotlinx-jvm:${project.ktor_version}"
    include "io.ktor:ktor-events-jvm:${project.ktor_version}"
    include "io.ktor:ktor-server-html-builder-jvm:${project.ktor_version}"
    include "org.jetbrains.kotlinx:kotlinx-html-jvm:0.12.0"
    String nettyVersion = "4.1.119.Final"
    include "io.netty:netty-codec-http2:$nettyVersion"
    include "io.netty:netty-codec:$nettyVersion"
    include "io.netty:netty-codec-http:$nettyVersion"
    include "org.eclipse.jetty.alpn:alpn-api:1.1.3.v20160715"
    include "io.netty:netty-transport-native-kqueue:$nettyVersion"
    include "io.netty:netty-transport-classes-kqueue:$nettyVersion"
}

loom {
    accessWidenerPath = file("src/main/resources/brightereconomy.accesswidener")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = 21
    }
}

java {
//    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
