# Done to increase the memory available to gradle.
org.gradle.jvmargs             = -Xmx2G
org.gradle.parallel            = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache = false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version              = 1.21.8
# For MC 1.21.11+, we'll need to migrate to Mojang mappings: https://docs.fabricmc.net/develop/migrating-mappings/
yarn_mappings                  = 1.21.8+build.1
loader_version                 = 0.18.2
fabric_version                 = 0.136.1+1.21.8
loom_version                   = 1.13-SNAPSHOT
# https://modrinth.com/mod/fabric-language-kotlin/versions
fabric_kotlin_version          = 1.13.7+kotlin.2.2.21
kotlin_version                 = 2.2.21

# Mod Properties
mod_version                    = 1.0.0
maven_group                    = brightspark.brightereconomy
archives_base_name             = brighter-economy

# Dependencies
# https://modrinth.com/mod/owo-lib/versions?l=fabric
owo_version                    = 0.12.23+1.21.8
# https://github.com/lucko/fabric-permissions-api/blob/master/USAGE.md
permissions_api_version        = 0.4.0
modmenu_version                = 15.0.1

ktor_version                   = 3.3.3
exposed_version                = 1.0.0-rc-4
sqlite_version                 = 3.51.1.0
mysql_version                  = 8.0.33
