openapi: 3.0.3
info:
  title: Brighter Economy API
  description: Backend API for the Brighter Economy dashboard
  version: 1.0.0
servers:
  - url: http://127.0.0.1:25570/api
security:
  - BasicAuth: [ ]

paths:
  /api/user-info:
    get:
      description: Gets basic user info if successfully authenticated
      tags: [ user-info ]
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                Success:
                  value: admin
                Failure:
                  value: null
  /api/configs:
    get:
      description: Gets all configs
      tags: [ configs ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Config"
  /api/configs/{key}:
    get:
      description: Gets a config by its key
      tags: [ configs ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Config"
    put:
      description: Sets a config by its key
      tags: [ configs ]
      requestBody:
        description: The config value
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: OK
  /api/accounts:
    get:
      description: Gets all accounts
      tags: [ accounts ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /api/accounts/{uuid}:
    get:
      description: Gets an account by player UUID
      tags: [ accounts ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: uuid
          required: true
          description: Player UUID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
  /api/accounts/{uuid}/transactions:
    get:
      description: Gets all transactions for the account
      tags: [ accounts ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: uuid
          required: true
          description: Player UUID
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
          required: false
          description: Maximum number of values to retrieve (default 10)
        - in: query
          name: sort
          schema:
            type: string
            enum: [ asc, desc ]
          required: false
          description: Whether to sort the transactions by timestamp ascending or descending (default "desc")
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /api/accounts/{uuid}/balance:
    put:
      description: Set an account's balance by player UUID
      tags: [ accounts ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: uuid
          required: true
          description: Player UUID
      requestBody:
        description: The amount of money to set the account's balance to
        required: true
        content:
          text/plain:
            schema:
              type: integer
              format: int64
      responses:
        "200":
          description: OK
  /api/transactions:
    get:
      description: Gets all transactions
      tags: [ transactions ]
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
          required: false
          description: Maximum number of values to retrieve (default 10)
        - in: query
          name: sort
          schema:
            type: string
            enum: [ asc, desc ]
          required: false
          description: Whether to sort the transactions by timestamp ascending or descending (default "desc")
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /api/shops:
    get:
      description: Gets all shops
      tags: [ shops ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Shop"
  /api/items:
    get:
      description: Gets all item IDs
      tags: [ items ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/items/{id}/name:
    get:
      description: Gets the English localisation for the item name
      tags: [ items ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: uuid
          required: true
          description: Item ID
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Config:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        type:
          type: string
          enum: [ BOOLEAN, INTEGER, LONG, STRING, ENUM, LIST ]
        possibleValues:
          type: array
          nullable: true
          items:
            type: string
    Account:
      type: object
      properties:
        uuid:
          type: uuid
        username:
          type: string
        locked:
          type: boolean
        money:
          type: integer
          format: int64
        moneyFormatted:
          type: string
    ItemStack:
      type: object
      properties:
        item:
          type: string
        count:
          type: integer
          format: int32
        customName:
          type: string
          nullable: true
        enchantments:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              level:
                type: integer
                format: int32
                nullable: true
        lore:
          type: string
          nullable: true
    Transaction:
      type: object
      properties:
        id:
          type: uuid
        type:
          type: string
          enum: [ TRANSFER, PURCHASE, MODIFY ]
        shopId:
          type: uuid
          nullable: true
        participants:
          type: string
          enum: [ PLAYERS, TO_NULL, FROM_NULL ]
        uuidFrom:
          type: uuid
          nullable: true
        uuidTo:
          type: uuid
          nullable: true
        nameFrom:
          type: string
          nullable: true
        nameTo:
          type: string
          nullable: true
        money:
          type: integer
          format: int64
        itemStack:
          $ref: "#/components/schemas/ItemStack"
          nullable: true
        timestamp:
          type: integer
          format: int64
    Shop:
      type: object
      properties:
        id:
          type: uuid
        ownerUuid:
          type: uuid
        ownerName:
          type: uuid
          nullable: true
        dimension:
          type: string
        position:
          type: object
          properties:
            x:
              type: integer
              format: int32
            y:
              type: integer
              format: int32
            z:
              type: integer
              format: int32
        itemStack:
          $ref: "#/components/schemas/ItemStack"
        price:
          type: integer
          format: int32
